let movies = [
    {
        id: 1,
        cat:"Chiếu rạp",
        title_movie: "Way Down (2021)",
        img_movie: "./images/allmovies/sieutrom.jpg",
        start: 9.8,
        hd:"HD | VIETSUB",
        heart: 983,
        times: "1h 58m",
        age: "16+",

    },
    {
        id: 2,
        cat:"Chiếu rạp",
        title_movie: "Mulan 2020",
        img_movie: "./images/allmovies/mulan.jpg",
        start: 9.7,
        hd:"HD | VIETSUB",
        heart: 864,
        times: "2h",
        age: "14+",

    },
    {
        id: 3,
        cat:"Chiếu rạp",
        title_movie: "Evil Expeller (2021)",
        img_movie: "./images/allmovies/bantaydietquy.jpg",
        start: 9.0,
        hd:"HD | TRAILER",
        heart: 762,
        times: "1h38m",
        age: "19+",

    },
    {
        id: 4,
        cat:"Chiếu rạp",
        title_movie: "Your Eyes Tell",
        img_movie: "./images/allmovies/thanhamtrongmatem.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 624,
        times: "2h10m",
        age: "15+",

    },
    {
        id: 5,
        cat:"Chiếu rạp",
        title_movie: "Land (2021)",
        img_movie: "./images/allmovies/vungdat.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 779,
        times: "1h58m",
        age: "16+",

    },
    {
        id: 6,
        cat:"Chiếu rạp",
        title_movie: "Onward (2020)",
        img_movie: "./images/allmovies/truytimphepthuat.jpg",
        start: 9.9,
        hd:"HD | TRAILER",
        heart: 913,
        times: "2h 5m",
        age: "18+",

    },
    {
        id: 7,
        cat:"Anime",
        title_movie: "Dragon, Ie wo Kau",
        img_movie: "./images/allmovies/dragonlewokau.jpg",
        start: 9.2,
        hd:"HD | VIETSUB",
        heart: 662,
        times: "1h 52m",
        age: "14+",

    },
    {
        id: 8,
        cat:"Anime",
        title_movie: "Shaman King 2021",
        img_movie: "./images/allmovies/vuaphapthuat.jpg",
        start: 9.1,
        hd:"HD | VIETSUB",
        heart: 934,
        times: "2h 15m",
        age: "14+",

    },
    {
        id: 9,
        cat:"Anime",
        title_movie: "Detective Conan",
        img_movie: "./images/allmovies/conan.jpg",
        start: 9.9,
        hd:"HD | VIETSUB",
        heart: 736,
        times: "1h 43m",
        age: "16+",

    },
    {
        id: 10,
        cat:"Anime",
        title_movie: "Seijo no Maryoku wa Bannou Desu",
        img_movie: "./images/allmovies/10.jpg",
        start: 9.4,
        hd:"HD | VIETSUB",
        heart: 884,
        times: "2h 2p",
        age: "16+",

    },
    {
        id: 11,
        cat:"Anime",
        title_movie: "The Princess of Snow and Blood",
        img_movie: "./images/allmovies/11.jpg",
        start: 9.5,
        hd:"HD | TRAILER",
        heart: 924,
        times: "2h 20m",
        age: "18+",

    },
    {
        id: 12,
        cat:"Anime",
        title_movie: "The Slime Diaries: That Time",
        img_movie: "./images/allmovies/12.jpg",
        start: 9.5,
        hd:"HD | TRAILER",
        heart: 781,
        times: "2h 11m",
        age: "16+",

    },
    {
        id: 13,
        cat:"Phim Lẻ",
        title_movie: "Those Who Wish Me Dead (2021)",
        img_movie: "./images/allmovies/13.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 625,
        times: "2h 18m",
        age: "16+",

    },
    {
        id: 14,
        cat:"Phim Lẻ",
        title_movie: "Blast Beat 2021",
        img_movie: "./images/allmovies/14.jpg",
        start: 9.5,
        hd:"HD | TRAILER",
        heart: 847,
        times: "1h 57m",
        age: "16+",

    },
    {
        id: 15,
        cat:"Phim Lẻ",
        title_movie: "August Never Ends 2021",
        img_movie: "./images/allmovies/15.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 593,
        times: "2h 20m",
        age: "16+",

    },
    {
        id: 16,
        cat:"Phim Lẻ",
        title_movie: "Happily (2021)",
        img_movie: "./images/allmovies/16.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 726,
        times: "1h 38m",
        age: "18+",

    },
    {
        id: 17,
        cat:"Phim Lẻ",
        title_movie: "Nobody (2021)",
        img_movie: "./images/allmovies/17.jpg",
        start: 9.5,
        hd:"HD | TRAILER",
        heart: 886,
        times: "1h 48m",
        age: "16+",

    },
    {
        id: 18,
        cat:"Phim Lẻ",
        title_movie: "I Love Catman 2019",
        img_movie: "./images/allmovies/18.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 1102,
        times: "2h 12m",
        age: "14+",

    }
]

let slides = [
    {
        id: 1,
        title_slide: "Moonlight (2021)",
        description: "Phim được chuyển thể từ tiểu thuyết <Khúc Biến Tấu Ánh Trăng> của tác giả Thanh Mỗi Câu chuyện tình yêu vui vẻ của nam tác giả đại thần và nữ biên tập mới hoạt bát đáng yêu...",
        img_slide: "./images/slide/moonlight.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 1067,
        times: "1h 30m",
        age: "16+",

    },
    {
        id: 2,
        title_slide: "Use For My Talent",
        description: "Cố Nhân Tề khi vừa sinh ra gia đình đã không toàn vẹn, phải sống cô lập khép kín với mọi người xung quanh, mắc chứng bệnh sạch sẽ nghiêm trọng...",
        img_slide: "./images/slide/useformytalen.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 957,
        times: "1h 54m",
        age: "18+",

    },
    {
        id: 3,
        title_slide: "Mouse (2021)",
        description: "Bộ phim \"Mouse / Kẻ Săn Người\" có nội dung kể về một câu chuyện đầy căng thẳng bắt đầu từ câu hỏi thú vị: Điều gì sẽ xảy ra nếu chúng ta có thể sàng lọc những kẻ rối loạn nhân cách trước?...",
        img_slide: "./images/slide/mouse.jpg",
        start: 9.5,
        hd:"HD | VIETSUB",
        heart: 1028,
        times: "2h 10p",
        age: "16+",

    }
]